# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-rest-api

provider:
  name: aws
  runtime: nodejs8.8 # set nodejs runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions:
  hello:
    handler: handler.hello

  create:
    handler: handler.create # points to exported create function in handler.js
    events:
      - http:
        path: notes # path will be domain.name.com/dev/notes
        method: post
        cors: true

  getOne:
    handler: handler.getOne
    events:
      - http:
        path: notes/{id} # path will be domain.name.com/dev/notes/1
        method: get
        cors: true

  getAll:
    handler: handler.getAll
    events:
      - http:
        path: notes # path will be domain.name.com/dev/notes
        method: get
        cors: true
  
  update:
    handler: handler.update
    events:
      - http:
        path: notes/{id} # path will be domain.name.com/dev/notes/1
        method: put
        cors: true

  delete:
    handler: handler.delete
    events:
      - http:
        path: notes/{id} # path will be domain.name.com/dev/notes/1
        method: delete
        cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation
